# Generated by Django 4.1.5 on 2023-02-14 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=800, verbose_name='作品名')),
                ('pub_date', models.DateField(verbose_name='公開日')),
                ('original_title', models.CharField(max_length=800, verbose_name='オリジナル作品名')),
                ('poster_path', models.TextField(null=True, verbose_name='ポスター画像パス')),
                ('original_language', models.CharField(max_length=2, verbose_name='劇場')),
                ('overview', models.TextField(null=True, verbose_name='あらすじ')),
                ('checkin_count', models.IntegerField(default=0, verbose_name='チェックイン回数')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('checkin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_datetime', models.DateTimeField(verbose_name='鑑賞日時')),
                ('theatre', models.CharField(max_length=200, verbose_name='劇場')),
                ('comment', models.TextField(null=True, verbose_name='感想')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreCheckIn.movies')),
            ],
        ),
    ]
