# Generated by Django 4.1.5 on 2023-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreCheckIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkins',
            name='movie_title',
            field=models.CharField(default=0, max_length=800),
            preserve_default=False,
        ),
    ]
