# Generated by Django 4.1.5 on 2023-02-27 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theatreCheckIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='movies',
            name='now_playing',
            field=models.BooleanField(default=True, verbose_name='公開中フラグ'),
        ),
        migrations.AddField(
            model_name='movies',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='checkins',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='感想'),
        ),
    ]
