# Generated by Django 4.1.5 on 2023-03-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreCheckIn', '0002_movies_created_datetime_movies_now_playing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='original_language',
            field=models.CharField(max_length=2, verbose_name='オリジナル言語'),
        ),
    ]
