# Generated by Django 4.1.5 on 2023-07-31 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatreCheckIn', '0005_rename_overview_movies_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='discription',
            new_name='description',
        ),
    ]
