# Generated by Django 4.1.5 on 2023-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreCheckIn', '0006_rename_discription_movies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
